TimeTrack.Server.MVC/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using TimeTrack.Server.MVC.Areas.HelpPage.ModelDescriptions;
using TimeTrack.Server.MVC.Areas.HelpPage.Models;

namespace TimeTrack.Server.MVC.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

TimeTrack.Server.MVC/Controllers/TimesheetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimeTrack.Model;
using TimeTrack.Server.MVC.TimeTrackServiceReference;

namespace TimeTrack.Server.MVC.Controllers
{
    public class TimesheetsController : Controller
    {
        private TimeTrackServiceClient serviceClient = new TimeTrackServiceClient();

        // GET: Timesheets
        public ActionResult Index()
        {
            var transactions = serviceClient.GetTimeSheets();
            return View(transactions.ToList());
        }

        // GET: Timesheets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Timesheet timesheet = serviceClient.GetTimeSheetById(id.Value);
            if (timesheet == null)
            {
                return HttpNotFound();
            }
            return View(timesheet);
        }

        // GET: Timesheets/Create
        public ActionResult Create()
        {
            ViewBag.FkEmployee = new SelectList(serviceClient.GetEmployees(), "Id", "FullName");
            ViewBag.FkProject = new SelectList(serviceClient.GetProjects(), "Id", "Name");
            return View();
        }

        // POST: Timesheets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FkEmployee,FkProject,Date,SpendTime,Notes")] Timesheet timesheet)
        {
            if (ModelState.IsValid)
            {
                serviceClient.AddTimesheet(timesheet);                
                return RedirectToAction("Index");
            }

            ViewBag.FkEmployee = new SelectList(serviceClient.GetEmployees(), "Id", "FullName", timesheet.FkEmployee);
            ViewBag.FkProject = new SelectList(serviceClient.GetProjects(), "Id", "Name", timesheet.FkProject);
            return View(timesheet);
        }

        // GET: Timesheets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Timesheet timesheet = serviceClient.GetTimeSheetById(id.Value);
            if (timesheet == null)
            {
                return HttpNotFound();
            }
            ViewBag.FkEmployee = new SelectList(serviceClient.GetEmployees(), "Id", "FullName", timesheet.FkEmployee);
            ViewBag.FkProject = new SelectList(serviceClient.GetProjects(), "Id", "Name", timesheet.FkProject);
            return View(timesheet);
        }

        // POST: Timesheets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FkEmployee,FkProject,Date,SpendTime,Notes")] Timesheet timesheet)
        {
            if (ModelState.IsValid)
            {
                serviceClient.UpdateTimeSheet(timesheet);
                return RedirectToAction("Index");
            }
            ViewBag.FkEmployee = new SelectList(serviceClient.GetEmployees(), "Id", "FullName", timesheet.FkEmployee);
            ViewBag.FkProject = new SelectList(serviceClient.GetProjects(), "Id", "Name", timesheet.FkProject);
            return View(timesheet);
        }

        // GET: Timesheets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Timesheet timesheet = serviceClient.GetTimeSheetById(id.Value);
            if (timesheet == null)
            {
                return HttpNotFound();
            }
            return View(timesheet);
        }

        // POST: Timesheets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            serviceClient.DeleteTimesheetById(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                serviceClient.Close();
            }
            base.Dispose(disposing);
        }
    }
}

TimeTrack.Server.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Timetrack", "Index", "Timesheets", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees", "Index", "Employees", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Projects", "Index", "Projects", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Timesheets", "Index", "Timesheets", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, null)</li>*@
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("SPAViews", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
    $(function () { // will trigger when the document is ready
        $('.datepicker').datepicker(); //Initialise any date pickers
    });
    </script>
</body>
</html>